# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "niram-css"
version = "0.2.0"
entrypoint = "src/lib.typ"
authors = ["nandac"]
license = "Unlicense"
description = "Use all 147 standardized CSS named colors directly in your Typst documents."
# homepage = ""
repository = "https://github.com/nandac/niram-css"
keywords = ["CSS colors", "SVG colors", "named colors", "web colors", "color palette"]
categories = ["components"]
disciplines = ["design", "drawing"]
compiler = "0.13.0"
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".gitignore",
  ".typstignore",
  "Justfile",
  "thumbnail-dark.svg",
  "thumbnail-light.svg",
  "thumbnail-2-dark.svg",
  "thumbnail-2-light.svg",
]
